version: '3'
services:
  eventstore:
    image: eventstore/eventstore:latest
    volumes:
      - ./data:/var/lib/eventstore
      - ./plugins:/usr/share/eventstore/plugins
    ports:
      - 2113:2113
    environment:
      - EVENTSTORE_CLUSTER_SIZE=3
#      - EVENTSTORE_CLUSTER_DNS=server1=192.168.3.16,server2=192.168.3.17,server3=192.168.3.18
      - EVENTSTORE_CLUSTER_GOSSIP_PORT=2112
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_GOSSIP_SEED=192.168.3.16:2113,192.168.3.17:2113,192.168.3.18:2113
      - EVENTSTORE_DISCOVER_VIA_DNS=false
#    extra_hosts:
#      - "server1:192.168.3.16"
#      - "server1:192.168.3.17"
#      - "server1:192.168.3.18"
    network_mode: "host"
#    dns:
#      - 192.168.3.2
